### ISSUE TITLE
dashboard improvement: nice form for order view, more info needed for order view in dashboard 

### ISSUE THREAD

**Issue by feiyanzhandui** [0xdyu/KD#18]

**Comment by feiyanzhandui** [comment]
build a form in dashboard page

**Comment by dorismeixing** [comment]
What to view in Dashboard and need to be shown as a clean & beautiful table:
- ID
- Sender name
- Sender Address Information
- Receiver Name
- Receiver Address Information
- Current Location
- Create Date
- Update Date

**Comment by feiyanzhandui** [comment]
open a new issue for dashboard info
