### ISSUE TITLE
System Language should be Chinese

### ISSUE THREAD

**Issue by dorismeixing** [0xdyu/KD#29]
All the parts of the system need to be translated into Chinese. I know Django has this Add-on function can do it. Or we just type Chinese directly. 

http://www.ziqiangxuetang.com/django/django-internationalization.html

**Comment by dorismeixing** [comment]
User Logout Page is in English. No automatic direct to Main Page.

**Comment by dorismeixing** [comment]
The Html part's translation is completed. The rest is assigned to 小坏.

**Comment by feiyanzhandui** [comment]
please recheck the html part, I changed couple of files without notice on translation @dorismeixing

**Comment by feiyanzhandui** [comment]
I am continue to work on translate for internal data

**Comment by feiyanzhandui** [comment]
done
