### ISSUE TITLE
Quote System

### ISSUE THREAD

**Issue by dorismeixing** [0xdyu/KD#36]
- Customer is able to create quote
- Need to manually manage the quotes from customer/ the quotes show in logistic board automatically?

**Comment by dorismeixing** [comment]
**## This is an online quote form of UPS. We can create us based on this.**
<img width="717" alt="screen shot 2016-07-26 at 8 45 07 pm" src="https://cloud.githubusercontent.com/assets/13142928/17160280/f6b8fc92-5371-11e6-9fca-7bbe339e03b0.png">
<img width="703" alt="screen shot 2016-07-26 at 8 45 16 pm" src="https://cloud.githubusercontent.com/assets/13142928/17160281/f6ba62ee-5371-11e6-9b03-e187633841c4.png">

**Comment by dorismeixing** [comment]
用户注册时，是否应该记录用户的地址。如有记录，创建订单的时候，就可以省下“Where is this shipment coming from"的信息输入，节省时间。若没有，订单可以在不登陆的时候，就创建订单。

**Comment by dorismeixing** [comment]
问题：
付款：1.货到付款 2.现在付款

**Comment by feiyanzhandui** [comment]
feature dropped
