### ISSUE TITLE
Quote front-end design.

### ISSUE THREAD

**Issue by dorismeixing** [0xdyu/KD#37]
- need to match our theme but simple format.
- Doris wants to learn from other sites' design

**Comment by dorismeixing** [comment]
Also need to design the customer usage flow.

**Comment by dorismeixing** [comment]
**## This is an online quote form of UPS. We can create us based on this.**
<img width="717" alt="screen shot 2016-07-26 at 8 45 07 pm" src="https://cloud.githubusercontent.com/assets/13142928/17160280/f6b8fc92-5371-11e6-9fca-7bbe339e03b0.png">
<img width="703" alt="screen shot 2016-07-26 at 8 45 16 pm" src="https://cloud.githubusercontent.com/assets/13142928/17160281/f6ba62ee-5371-11e6-9b03-e187633841c4.png">

**Comment by feiyanzhandui** [comment]
feature droped
