### ISSUE TITLE
account dashboard 

### ISSUE THREAD

**Issue by feiyanzhandui** [0xdyu/KD#4]
a dashboard for Shipping Customers to manage orders

Dashboard elements:
- Order Creation feature(A button of creation)
- The list of all orders
- Order searching 
- Order edition feature(User can edit the order in the same page.)
- Order deletion feature

**Comment by feiyanzhandui** [comment]
also order searching needed in dashboard

**Comment by dorismeixing** [comment]
User Profile page.
