### ISSUE TITLE
Order Filter on Dashboard

### ISSUE THREAD

**Issue by dorismeixing** [0xdyu/KD#48]
A filter for the shipping users to look up a particular order on their dashboard.(enter a number, and the specific order will show up.)

Pro:
look up an order easily while there are lots of orders listed.

How it may look like:
<img width="1125" alt="screen shot 2016-08-24 at 9 35 55 pm" src="https://cloud.githubusercontent.com/assets/13142928/18036090/c4280d58-6d30-11e6-9d77-37d0dcd5391a.png">

How it works:
<img width="1120" alt="screen shot 2016-08-24 at 9 36 16 pm" src="https://cloud.githubusercontent.com/assets/13142928/18036089/c427f55c-6d30-11e6-8b0a-a77aeab08ae8.png">

**Comment by feiyanzhandui** [comment]
added a search option
